# Generated by Django 4.2.1 on 2024-01-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='basket',
            new_name='cart',
        ),
    ]
