# Generated by Django 4.2.1 on 2024-01-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justsite', '0009_alter_comments_options_and_more'),
        ('users', '0005_alter_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='justsite.items'),
        ),
    ]
