# Generated by Django 4.2.1 on 2024-01-14 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('justsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-time_create'], 'verbose_name': 'Товары магазина', 'verbose_name_plural': 'Товары магазина'},
        ),
        migrations.AlterModelManagers(
            name='items',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='justsite.category', verbose_name='Категория'),
        ),
    ]
