# Generated by Django 4.2.1 on 2024-01-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justsite', '0004_alter_items_cat_alter_items_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(blank=True, default=100, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
