# Generated by Django 4.2.1 on 2024-01-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justsite', '0006_alter_items_cat_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='justsite.category', verbose_name='Категория'),
        ),
    ]
