# Generated by Django 4.2.1 on 2024-01-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justsite', '0009_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
