# Generated by Django 4.2.1 on 2024-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justsite', '0010_items_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка:'),
        ),
    ]
